ALTER TABLE book
ALTER description VARCHAR2(10000);

INSERT INTO book (`id`, `author`, `isbn`, `publisher`, `quantity`, `title`, `img`, `description`) VALUES
(1, 'Dante Alighieri', '9788800222372', 'Mondadori Education', 10, 'Divina Commedia - Volume unico. Con Me book e Contenuti Digitali Integrativi online', 'https://www.salernoeditrice.it/wp-content/uploads/2018/09/commedia_sito.jpg', 'La Comedìa, o Commedia, conosciuta soprattutto come Divina Commedia, è un poema allegorico-didascalico di Dante Alighieri, scritto in terzine incatenate di endecasillabi (poi chiamate per antonomasia terzine dantesche) in lingua volgare fiorentina.'),
(2, 'Antoine de Saint-Exupéry', '9788800222373', 'Newton Compton Editori', 5, 'Il Piccolo Principe', 'https://images-na.ssl-images-amazon.com/images/I/71iQfQYj0cL.jpg', 'Il piccolo principe (Le Petit Prince) è un racconto di Antoine de Saint-Exupéry, il più conosciuto della sua produzione letteraria, pubblicato il 6 aprile 1943 a New York da Reynal & Hitchcock nella traduzione inglese (The Little Prince, tradotto dal francese da Katherine Woods) e qualche giorno dopo sempre da Reynal & Hitchcock nell originale francese. Solo nel 1945, dopo la scomparsa dell autore, fu pubblicato in Francia a Parigi da Gallimard. Il testo e i disegni sono stati realizzati in vari siti di New York, la maggior parte nella residenza Bevin House di Asharoken, Long Island.'),
(4, 'George Orwell', '3548204562', 'Longman', 4, '1984', 'https://pictures.abebooks.com/isbn/9783548204567-it-300.jpg', '1984 (Nineteen Eighty-Four) è un romanzo distopico di George Orwell, pubblicato nel 1949. Le Monde lo posiziona al 22º posto della classifica dei 100 migliori libri scritti nel ventesimo secolo.'),
(5, 'Austen, Jane', '8863113831', 'Liberamente', 8, 'Orgoglio e pregiudizio. Ediz. integrale', 'https://pictures.abebooks.com/inventory/md/md30493868008.jpg','Orgoglio e pregiudizio (Pride and Prejudice) è uno dei più celebri romanzi della scrittrice inglese Jane Austen, pubblicato il 28 gennaio 1813.'),
(6, 'Brontë, Emily', '8883371291', 'Crescere', 6, 'Cime tempestose', 'https://pictures.abebooks.com/isbn/9788883371295-it-300.jpg','Cime tempestose (Wuthering Heights) è l unico romanzo di Emily Brontë, scritto fra l ottobre 1845 e il giugno 1846. Venne pubblicato per la prima volta nel 1847, sotto lo pseudonimo di Ellis Bell, mentre una seconda edizione postuma fu curata da sua sorella Charlotte nel 1850.Il titolo viene dal nome di una delle tre principali ambientazioni del libro (Wuthering Heights, Gimmerton, Thrushcross Grange) il casale nella brughiera dello Yorkshire originariamente di proprietà degli Earnshaw, dove fu allevato Heathcliff e dove la storia si sviluppa.'),
(7, 'Macchiavelli, Niccolo', '8863113882', 'Liberamente', 1, 'Il principe', 'https://pictures.abebooks.com/inventory/md/md30543412264.jpg','Il principe (titolo assegnato nell edizione originale postuma di Antonio Blado e poi unanimemente adottato, ma il titolo originario era in lingua latina: De Principatibus, "Sui principati") è un saggio critico di dottrina politica scritto da Niccolò Machiavelli probabilmente tra la seconda metà del 1513 e l inizio del 1514, nel quale espone le caratteristiche dei principati e dei metodi per conquistarli e mantenerli. Si tratta senza dubbio della sua opera più nota e celebrata, quella dalle cui massime (spesso superficialmente interpretate) sono nati il sostantivo "machiavellismo" e l aggettivo "machiavellico".'),
(8, 'Rowling, J. K.', '0747558191', 'Bloomsbury Publishing', 12, 'Harry Potter and the Philosophers Stone', 'https://pictures.abebooks.com/isbn/9780747558194-it-300.jpg','Harry Potter è una serie di romanzi fantasy scritta da J. K. Rowling, incentrata sulle avventure del giovane mago Harry Potter e dei suoi migliori amici Ron Weasley ed Hermione Granger, studenti della Scuola di Magia e Stregoneria di Hogwarts. Il mondo magico nel quale è ambientata la saga consiste in una società parallela che vive celata al resto del mondo reale, quello delle persone comuni, che vengono definite "babbani". L arco narrativo segue principalmente lo scontro tra il protagonista e il mago oscuro Lord Voldemort, desideroso di conquistare il mondo magico e l immortalità.'),
(9, 'Kant, Immanuel', '8835032059', 'Laterza', 7, 'Critica della ragion pratica', 'https://pictures.abebooks.com/inventory/md/md30946534357.jpg','La Critica della ragion pura (titolo originale Kritik der reinen Vernunft) è l opera maggiormente nota di Immanuel Kant. L opera, pubblicata nel 1781, ed in seguito ampiamente rimaneggiata nella seconda edizione del 1787, è suddivisa in due parti:La Dottrina trascendentale degli elementi e  La Dottrina trascendentale del metodo.'),
(10, 'Omero', '881801837X', 'Rusconi Libri', 10, 'Iliade', 'https://pictures.abebooks.com/isbn/9788818018370-it-300.jpg','L Iliade (in greco antico: Ἰλιάς, Iliás) è un poema epico in esametri dattilici, tradizionalmente attribuito a Omero. Ambientato ai tempi della guerra di Troia, città da cui prende il nome, narra gli eventi accaduti nei cinquantuno giorni del decimo e ultimo anno di guerra, in cui l ira di Achille è l argomento portante. Opera antica e complessa, è un caposaldo della letteratura greca e occidentale.'),
(11, 'Virgilio', '2560731040778', 'Sansoni', 0, 'L Eneide', 'https://pictures.abebooks.com/inventory/md/md17145207022.jpg','L Eneide (in latino: Aeneis) è un poema epico della cultura latina scritto dal poeta Publio Virgilio Marone tra il 29 a.C. e il 19 a.C. Narra la leggendaria storia dell eroe troiano Enea (figlio di Anchise e della dea Venere) che riuscì a fuggire dopo la caduta della città di Troia, e che viaggiò per il Mediterraneo fino ad approdare nel Lazio, diventando il progenitore del popolo romano.');

INSERT INTO `activetokens` (`tokenid`, `email`, `tk`) VALUES
(95, 'dario.tintore3@gmail.com', 'eyJhbGciOiJub25lIn0.eyJzdWIiOiJkYXJpby50aW50b3JlM0BnbWFpbC5jb20iLCJhdWQiOiJ0b2tlbi1nZW5lcmF0aW9uIiwiMWQyMCI6MTMsImlhdCI6MTY0NjIyOTk1MiwiZXhwIjoxNjQ2MjMwMDEyfQ.'),
(96, 'test@test.it', 'eyJhbGciOiJub25lIn0.eyJzdWIiOiJ0ZXN0QHRlc3QuaXQiLCJhdWQiOiJ0b2tlbi1nZW5lcmF0aW9uIiwiMWQyMCI6MTEsImlhdCI6MTY0NjI0MTA2MywiZXhwIjoxNjQ2MjQxMTIzfQ.'),
(98, 'prova@test.it',  'eyJhbGciOiJub25lIn0.eyJzdWIiOiJwcm92YUB0ZXN0Lml0IiwiYXVkIjoidG9rZW4tZ2VuZXJhdGlvbiIsIjFkMjAiOjIsImlhdCI6MTY0NjI0MTc1NiwiZXhwIjoxNjQ2MjQxODE2fQ.'),
(109, 'test@test.com',  'eyJhbGciOiJub25lIn0.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiYXVkIjoidG9rZW4tZ2VuZXJhdGlvbiIsIjFkMjAiOjEwLCJpYXQiOjE2NDYyNDQyNjksImV4cCI6MTY0NjI0NDMyOX0.');

INSERT INTO `orders` (`id`, `email`, `isbn`, `quantity`, `date`,`shipped`) VALUES
(13, 'dario.tintore3@gmail.com', '9788800222372', 1, '2022-03-02 11:39:16', false),
(14, 'dario.tintore3@gmail.com', '9788800222372', 1, '2022-03-02 11:48:27', true),
(15, 'dario.tintore3@gmail.com', '9788800222373', 1, '2022-03-02 11:48:38', true),
(16, 'dario.tintore3@gmail.com', '9788800222373', 1, '2022-03-02 15:05:57', true),
(17, 'test@test.com','9788800222373', 1, '2022-03-02 15:05:57', false),
(18, 'test@test.com','9788800222373', 1, '2022-04-02 15:05:57', false);

INSERT INTO `users` (`userid`, `email`, `firstname`, `lastname`, `password`) VALUES
(1000, 'dariotintore2@gmail.com', NULL, NULL, '$2a$10$eKZFn0Ja5kCJSYJqAPMNu.eAWhnSWDSJ80aGbk0nC55cURrF4UTTK'),
(1001, 'test@test.com', NULL, NULL, '$2a$10$n4C83jnDebSPjtLS2NGHZeRBFjg9TuhWPjTGgpJ2.EySYDIFNsWAe'),
(1002, 'dario.tintore2@gmail.com', NULL, NULL, '$2a$10$JUwIr8fqIeJ/7XQH1skCLeKL7NwvLqcGDKLebJ/pS7jUScHAgTnHC'),
(1003, 'dario.tintore3@gmail.com', NULL, NULL, '$2a$10$36dGwEvfEOZOTrLnblnkkOtlFAfEJdoYe/UqJXlmwLWsahOy/QjXu'),
(1004, 'test@test.it', NULL, NULL, '$2a$10$G71eMdiSmSiF1uZCCFw18OnjeD1DBPTnswTczX2DSGqN9rJo1jmWm'),
(1005, 'prova@test.it', NULL, NULL, '$2a$10$ex76FDp3CPEvHxjJFWHiMeGwsjUMJRxLFtmLxaf8ABziVNf1jQbjC');
